<!-- form tag -->
<form class="form" id="custom-form-id" action="<?php echo $this->getUrl('simpleregistration/account/create'); ?>" method="post" autocomplete="off">
   <fieldset class="fieldset">
       <legend class="legend"><span><?php echo __('Test Registration Form') ?></span></legend><br>
        <div class="field required">
            <!-- form field -->
            <label for="firstname" class="label"><span><?php echo __('First Name') ?></span></label>
            <div class="control">
                <input type="text" name="firstname" id="firstname" value="" title="<?php echo __('First Name') ?>" class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <!-- form field -->
            <label for="lastname" class="label"><span><?php echo __('Last Name') ?></span></label>
            <div class="control">
                <input type="text" name="lastname" id="lastname" value="" title="<?php echo __('Last Name') ?>" class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <!-- form field -->
            <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" value="" title="<?php echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field required">
            <!-- form field -->
            <label for="phone" class="label"><span><?php echo __('Phone') ?></span></label>
            <div class="control">
                <input type="text" name="phone" id="phone" value="" title="<?php echo __('Phone') ?>" class="input-text" data-validate="{required:true}">
            </div>
        </div>
   </fieldset>
   <!-- submit button -->
   <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php  echo __('Submit') ?>"><span><?php echo __('Submit') ?></span></button>
        </div>
    </div>
</form>

<!-- enable javascript validation for custom-form-id -->
<script type="text/x-magento-init">
    {
        "#custom-form-id": {
            "validation": {}
        }
    }
</script>